root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
full_bin = "./tmp/main"
include_ext = ["go", "tpl", "tmpl", "html", "sql", "yaml", "yml", "json"]
exclude_dir = ["assets", "tmp", "docs"]
include_dir = []
exclude_file = []
delay = 500
stop_on_error = true
log = "air_errors.log"
send_interrupt = true
kill_delay = 500

[log]
time = true

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true 