codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        # Basic settings
        target: 80%
        threshold: 2%
        if_ci_failed: error
        # Only check coverage on these paths
        paths: 
          - "internal"
        # Exclude test files and generated files
        ignore:
          - "**/mock_*.go"
          - "**/*_test.go"
          - "**/docs"
          - "cmd"
    
    patch:
      default:
        # Coverage threshold for new code
        target: 80%
        # Allow the coverage to drop by 5% in new code
        threshold: 5%
        if_ci_failed: error
        paths:
          - "internal"

    changes: false

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  show_carryforward_flags: true

github_checks:
  annotations: true 